// ════════════════════════════════════════════════════════════════════════
//  gen_circle_tables.b — the unit-circle tables bplot's rasteriser draws
//  circles and arcs with.
//
//      bantu run scripts/gen_circle_tables.b
//
//  writes bantu-src/compiler/src/raster_tables.hpp (set OUT=<path> to write
//  elsewhere). Authoring-time tooling: it runs once, by hand, and its OUTPUT
//  is checked in. Nothing in the build or at run time runs it.
//
//  WHY A TABLE AND NOT cos()
//  bplot's PNG output must be byte-identical on Linux, macOS and Windows
//  (docs/bplot-raster-architecture.md §2). cos and sin are not correctly
//  rounded, and glibc, Apple's libm and the MSVC runtime disagree in the last
//  bit -- enough to move a vertex, change a coverage value, and change the
//  file. So the values are computed ONCE, here, and embedded as integer
//  literals. At run time the rasteriser only adds, multiplies and shifts.
//  (Regenerating on another platform may therefore change a last digit; the
//  checked-in header is the reference, not this script's output elsewhere.)
//
//  The values are Q30 fixed point: 1.0 is 1 << 30. Q30 leaves a full integer
//  bit plus the sign in an int32, and a radius error below 1e-9 of full scale
//  is far under the 1/256 of a pixel the rasteriser works to. The checks below
//  confirm each table is a circle to within a few parts in 1e10, and that the
//  quarter points are exactly 0 and 1 rather than something that merely rounds
//  to them.
// ════════════════════════════════════════════════════════════════════════

$ONE = 1073741824;   // 1 << 30

// Round half to even, as the original generator (Python's round) did, and
// never -0.
def roundEven($x) {
    $r = floor($x);
    $d = $x - $r;
    if ($d > 0.5 || ($d == 0.5 && $r % 2 != 0)) { $r = $r + 1; }
    return $r + 0;
}

// A non-negative integer as at least two digits.
def two($i) {
    if ($i < 10) { return "0" + str($i); }
    return str($i);
}

// "%.2f" for a non-negative number.
def fixed2($x) {
    $h = roundEven($x * 100);
    $f = $h % 100;
    return str(($h - $f) / 100) + "." + two($f);
}

// "%.1e" for a positive number: 4.5e-10.
def sci1($x) {
    $e = floor(log10($x));
    $m = roundEven($x / pow(10, $e) * 10);
    if ($m >= 100) { $m = roundEven($m / 10); $e = $e + 1; }
    $sign = "+";
    if ($e < 0) { $sign = "-"; }
    return str(($m - $m % 10) / 10) + "." + str($m % 10) + "e" + $sign + two(abs($e));
}

def table($n) {
    $cs = [];
    $sn = [];
    $worst = 0;
    $k = 0;
    while ($k < $n) {
        $c = roundEven(cos(2 * PI * $k / $n) * $ONE);
        $s = roundEven(sin(2 * PI * $k / $n) * $ONE);
        push($cs, $c);
        push($sn, $s);
        $worst = max($worst, abs(hypot($c, $s) - $ONE));
        $k = $k + 1;
    }
    // The quarter points are exact, not merely close: a circle that is a pixel
    // out at the top is a circle someone will notice.
    if ($cs[0] != $ONE || $sn[0] != 0) { throw "angle 0 must be (1, 0)"; }
    if ($sn[$n / 4] != $ONE || abs($cs[$n / 4]) > 1) { throw "a quarter turn must be (0, 1)"; }
    if ($cs[$n / 2] != 0 - $ONE || abs($sn[$n / 2]) > 1) { throw "a half turn must be (-1, 0)"; }
    if ($worst >= 0.00000001 * $ONE) { throw "N=" + str($n) + ": radius error " + str($worst); }
    return {"cos": $cs, "sin": $sn, "worst": $worst};
}

def row($name, $n, $vals) {
    $parts = [];
    each ($v in $vals) { push($parts, str($v)); }
    return "static const int32_t " + $name + str($n) + "[" + str($n) + "] = { " + join($parts, ", ") + " };";
}

$out = [
    "#pragma once",
    "// Generated by scripts/gen_circle_tables.b -- do not edit by hand.",
    "//",
    "// cos and sin at k * 2*pi / N, as Q30 fixed point (1.0 == 1 << 30), so the",
    "// rasteriser never calls a trigonometric function: libm disagrees in the last",
    "// bit between platforms, and a byte-identical PNG cannot afford that.",
    "",
    "#include <cstdint>",
    "",
    "namespace bplot_raster {",
    ""
];
each ($n in [16, 32, 64, 128, 256]) {
    $t = table($n);
    push($out, "// N = " + str($n) + ": worst radius error " + fixed2($t["worst"]) + " of " + str($ONE)
        + " (" + sci1($t["worst"] / $ONE) + ")");
    push($out, row("kCos", $n, $t["cos"]));
    push($out, row("kSin", $n, $t["sin"]));
    push($out, "");
}
push($out, "} // namespace bplot_raster");

$path = env("OUT");
if ($path == null || $path == "") { $path = "bantu-src/compiler/src/raster_tables.hpp"; }
writefile($path, join($out, "\n") + "\n", "wb");
print("wrote " + $path);
