#!/usr/bin/env python3
"""Generate the unit-circle tables bplot's rasteriser draws circles and arcs with.

    python3 scripts/gen_circle_tables.py > bantu-src/compiler/src/raster_tables.hpp

NOT PART OF THE BUILD, AND TO BE CONVERTED TO BANTU
---------------------------------------------------
This is authoring-time tooling: it runs once, by hand, and its OUTPUT is
checked in. No build step and nothing at run time touches Python. It is
written in Python only because that is what was to hand the day the tables were first needed, and it is meant to be rewritten in
Bantu -- everything it uses (cos, sin, PI, writefile) already exists, so this one is a direct translation.

WHY A TABLE AND NOT cos()
-------------------------
bplot's PNG output must be byte-identical on Linux, macOS and Windows
(docs/bplot-raster-architecture.md §2). `cos` and `sin` are not correctly
rounded, and glibc, Apple's libm and the MSVC runtime disagree in the last bit
-- which is enough to move a vertex, change a coverage value, change the
deflate stream and change the file. So the values are computed ONCE, here, and
embedded as integer literals. At run time the rasteriser only adds, multiplies
and shifts.

The values are Q30 fixed point: 1.0 is 1 << 30. Q30 leaves a full integer bit
plus the sign in an int32, and a radius error below 1e-9 of full scale is far
under the 1/256 of a pixel the rasteriser works to.

A resolution is chosen from the radius so the chord error stays under a
sixteenth of a pixel; the checks below confirm each table is a circle to within
a few parts in 1e10, and that the quarter points are exactly 0 and 1 rather
than something that merely rounds to them.
"""

import math
import sys

RESOLUTIONS = (16, 32, 64, 128, 256)
ONE = 1 << 30


def table(n):
    cos = [round(math.cos(2 * math.pi * k / n) * ONE) for k in range(n)]
    sin = [round(math.sin(2 * math.pi * k / n) * ONE) for k in range(n)]

    # The quarter points are exact, not merely close: a circle that is a pixel
    # out at the top is a circle someone will notice.
    assert cos[0] == ONE and sin[0] == 0, "angle 0 must be (1, 0)"
    assert sin[n // 4] == ONE and abs(cos[n // 4]) <= 1, "a quarter turn must be (0, 1)"
    assert cos[n // 2] == -ONE and abs(sin[n // 2]) <= 1, "a half turn must be (-1, 0)"

    worst = max(abs(math.hypot(c, s) - ONE) for c, s in zip(cos, sin))
    assert worst < 1e-8 * ONE, f"N={n}: radius error {worst}"
    return cos, sin, worst


def main():
    out = sys.stdout
    out.write("#pragma once\n")
    out.write("// Generated by scripts/gen_circle_tables.py -- do not edit by hand.\n")
    out.write("//\n")
    out.write("// cos and sin at k * 2*pi / N, as Q30 fixed point (1.0 == 1 << 30), so the\n")
    out.write("// rasteriser never calls a trigonometric function: libm disagrees in the last\n")
    out.write("// bit between platforms, and a byte-identical PNG cannot afford that.\n")
    out.write("\n#include <cstdint>\n\nnamespace bplot_raster {\n\n")
    for n in RESOLUTIONS:
        cos, sin, worst = table(n)
        out.write(f"// N = {n}: worst radius error {worst:.2f} of {ONE} ({worst / ONE:.1e})\n")
        for name, vals in (("kCos", cos), ("kSin", sin)):
            body = ", ".join(str(v) for v in vals)
            out.write(f"static const int32_t {name}{n}[{n}] = {{ {body} }};\n")
        out.write("\n")
    out.write("} // namespace bplot_raster\n")


if __name__ == "__main__":
    main()
